pub mod agents;
pub mod approval;
pub mod cron;
pub mod files;
pub mod image_generate_models;
pub mod images;
pub mod inbox;
pub mod llm;
pub mod mcp;
pub mod plugins;
pub mod sessions;
pub mod transcribe_models;
pub mod tts_models;
pub mod ws;

use std::sync::Arc;

use axum::{
    Router,
    extract::State,
    http::StatusCode,
    response::{IntoResponse, Response},
    routing::{delete, get, patch, post, put},
};

use crate::server::AppState;

pub fn router() -> Router<AppState> {
    Router::new()
        .route("/agents",                       get(agents::list))
        .route("/agents/{id}",                  get(agents::get))
        .route("/agents/{id}/icon",             get(agents::icon))
        .route("/sessions",                             post(sessions::create))
        .route("/web/messages",                         get(sessions::web_messages))
        .route("/{source}/messages",                    get(sessions::source_messages))
        .route("/web/tools/{tool_call_id}/resolve",     post(sessions::web_resolve_tool))
        .route("/ws",                                   get(ws::handler))
        // LLM selector (for copilot dropdown)
        .route("/llm/models/selector",          get(llm::selector))
        // LLM providers
        .route("/llm/providers",                get(llm::list_providers).post(llm::create_provider))
        .route("/llm/providers/{id}",           get(llm::get_provider).put(llm::update_provider).delete(llm::delete_provider))
        .route("/llm/providers/{id}/models",            get(llm::provider_models))
        // LLM models
        .route("/llm/models",                   get(llm::list_models).post(llm::create_model))
        .route("/llm/models/{id}",              get(llm::get_model).put(llm::update_model).delete(llm::delete_model))
        // Transcription models
        .route("/transcribe/models",            get(transcribe_models::list_models).post(transcribe_models::create_model))
        .route("/transcribe/models/{id}",       get(transcribe_models::get_model).put(transcribe_models::update_model).delete(transcribe_models::delete_model))
        // Image generation models
        .route("/image-generate/models",        get(image_generate_models::list_models).post(image_generate_models::create_model))
        .route("/image-generate/models/{id}",   get(image_generate_models::get_model).put(image_generate_models::update_model).delete(image_generate_models::delete_model))
        // TTS models
        .route("/tts/models",                   get(tts_models::list_models).post(tts_models::create_model))
        .route("/tts/models/{id}",              get(tts_models::get_model).put(tts_models::update_model).delete(tts_models::delete_model))
        // Cron jobs
        .route("/cron/jobs",                    get(cron::list))
        .route("/cron/jobs/{id}",               delete(cron::delete_job))
        .route("/cron/jobs/{id}/toggle",        post(cron::toggle))
        // Agent Inbox — unified pending approvals + clarifications
        .route("/inbox",                                          get(inbox::list))
        .route("/inbox/approvals/{request_id}/resolve",           post(inbox::resolve_approval))
        .route("/inbox/clarifications/{request_id}/resolve",      post(inbox::resolve_clarification))
        // Approval — pending list + cross-session resolve (kept for backwards compat)
        .route("/approval/pending",             get(approval::list_pending))
        .route("/approval/pending/{request_id}/resolve", post(approval::resolve_pending))
        // Approval rules
        .route("/approval/rules",               get(approval::list_rules).post(approval::create_rule))
        .route("/approval/rules/{id}",          put(approval::update_rule).delete(approval::delete_rule))
        .route("/approval/tools",               get(approval::list_tools))
        // MCP
        .route("/mcp/servers",                  get(mcp::list_servers))
        // TIC
        .route("/tic/trigger",                  post(tic_trigger))
        // Plugins
        .route("/plugins",                      get(plugins::list))
        .route("/plugins/{id}",                 put(plugins::update))
        // Images (generated by image_generate tool)
        .route("/images/{task_id}",             get(images::get_image))
        // Files
        .route("/files",                        get(files::list_files))
        .route("/file",                         get(files::get_file))
        .route("/file",                         post(files::create_file))
        .route("/file",                         put(files::save_file))
        .route("/file",                         patch(files::rename_file))
        .route("/file",                         delete(files::delete_file))
}

async fn tic_trigger(State(state): State<AppState>) -> impl IntoResponse {
    tokio::spawn(async move {
        Arc::clone(&state.tic_manager).tick_now().await;
    });
    StatusCode::ACCEPTED
}

pub struct ApiError {
    status:  StatusCode,
    message: String,
}

impl ApiError {
    pub fn bad_request(msg: impl Into<String>) -> Self {
        Self { status: StatusCode::BAD_REQUEST, message: msg.into() }
    }

    pub fn not_found(msg: impl Into<String>) -> Self {
        Self { status: StatusCode::NOT_FOUND, message: msg.into() }
    }
}

impl IntoResponse for ApiError {
    fn into_response(self) -> Response {
        (self.status, self.message).into_response()
    }
}

impl<E: Into<anyhow::Error>> From<E> for ApiError {
    fn from(e: E) -> Self {
        let err = e.into();
        tracing::error!(error = ?err, "internal API error");
        Self { status: StatusCode::INTERNAL_SERVER_ERROR, message: err.to_string() }
    }
}
